### ISSUE TITLE
[BUG] Videx-wellog git hub repository doesn't list releases properly

### ISSUE THREAD

**Issue by mirisb** [equinor/videx-wellog#284]
When a new videx release is created I want to visit: https://github.com/equinor/videx-wellog/releases to see what was updated since last release. Unfortunately this page has not been updated since 4 years ago, and the last released version there is 0.4.0. Videx' latest released version is actually 0.10.6.

Can this be fixed?

**Comment by GuillaumeVix** [comment]
Thank you for the suggestion.

We will look into it. We will add info for the current release and the next one to come, but do not intend to add release information retroactively - sorry for that.

_Suggested approach: either try to auto-generate the release or release every time a new package update/relevant PR has been made and add corresponding description._

**Comment by johannesleite** [comment]
@mirisb I made a summary release all the way from v0.4.0 and until current release, and we will continue to create releases from now on when we release a new version.
