### ISSUE TITLE
Snyk: videx-wellog - December 2024

### ISSUE THREAD

**Issue by GuillaumeVix** [equinor/videx-wellog#290]
## Description
Recurring task to fix videx-wellog vulnerabilities.

Have a look at the equinor/videx-wellog [vulnearibilities](https://app.snyk.io/org/videx/projects?groupBy=targets&before&after&searchQuery=&sortBy=highest+severity&filters[Show]=&filters[Integrations]=&filters[CollectionIds]=)

- [examples/storybook/package.json](https://app.snyk.io/org/videx/project/7c300ae6-937b-4821-9cd6-6ffa320dc2d0)
- [package.json](https://app.snyk.io/org/videx/project/74506eb6-512a-419e-8297-9f66428e0a4d)
- [Code Analysis](https://app.snyk.io/org/videx/project/2d7032b8-f8d0-4fba-bf40-1b495ddb4e79)

![Image](https://github.com/user-attachments/assets/60f45758-3f37-4768-869d-a95cc23f0aa6)

## How to test
Repository equinor/videx-wellog [vulnearibilities](https://app.snyk.io/org/videx/projects?groupBy=targets&before&after&searchQuery=&sortBy=highest+severity&filters[Show]=&filters[Integrations]=&filters[CollectionIds]=) should not have vulnerabilities equal or above 'Medium'.

## Acceptance criteria
1. Videx-wellog repository does not have any detected vulnerability equal or above 'Medium' (only 'low' are discarded)

**Comment by GuillaumeVix** [comment]
Also impacted by https://github.com/equinor/mad-project-rep/issues/6012

**Comment by tomktjemsland** [comment]
One high and two medium vulnerabilities remain. The medium ones are related to `inflight`, which will be fixed in newer versions of `jest`. The high one is related to `ws`, which will be fixed in a newer version of `jest-environment-jsdom`.

**Comment by ezarubina** [comment]
Not a part of 4.10.6 as we still use the older wellLog version (0.10.6) where the change is not included.
