### ISSUE TITLE
How to create tracks and add line plots

### ISSUE THREAD

**Issue by melikeercan** [equinor/videx-wellog#60]
I would like to use this library to plot my 2d well logs. I have been been trying to plot a simple 1 track 1 line plot but all i am seeing is a white canvas with nothing displayed. Your examples don't use your npm library and the parameters are not matching etc. Could you please provide us with some working examples? This repo seems like a great one but it clearly lacks documentation. Thanks in advance. 
Or maybe a youtube video of this examples would make more sense.

**Comment by Brynjulf** [comment]
Hi @melikeercan,

I have updated the example [react repository](https://github.com/equinor/react-videx-wellog-example) with a working example of the log viewer which features multiple tracks.

We are working on improving the documentation, and appreciate any and all input.

**Comment by Brynjulf** [comment]
Closing this, feel free to open a new issue if you feel there is something missing
