### ISSUE TITLE
Any examples with react ?

### ISSUE THREAD

**Issue by rumeshwick** [equinor/videx-wellog#62]

**Comment by Brynjulf** [comment]
Hi, i have created a bare bones [react app](https://github.com/equinor/react-videx-wellog-example) that shows how to plot some lines. The example itself is just a copy of one of our stories in storybook.

**Comment by rumeshwick** [comment]
@Brynjulf Thank you for the quick reply. But the issue is with the example where it creates Tracks. I also tried the examples which create Plots in canvas and that worked for me. But i had the issues with Log Viewer where it creates Tracks. I inspected the elements and i could see that Track title elements were created. But its content was empty. And the graph wasn't created at all.

**Comment by Brynjulf** [comment]
@rumeshwick ,

I have added an example of the log viewer (`Log Viewer > Log Viewer Horizontal` from storybook) in the react example repository. The main difference from the story and the react example is that storybook imports the styling as a part of the config whereas it should  be clearer in the react example in that it imports the styling directly into the file.

**Comment by rumeshwick** [comment]
@Brynjulf This is great. Thank you very much.
