### ISSUE TITLE
Logs with few data points, display problem. 

### ISSUE THREAD

**Issue by john-haugland** [equinor/videx-wellog#95]
When zooming into a track so that data-control points are outside the display area, the log curve automatically disappears. We need to turn off this behavior e.g. pr. graph/track to be able to display logs with few data points.

**Comment by Brynjulf** [comment]
Hi @john-haugland, there is an option for plots to filter away data points ([filterToScale](https://github.com/equinor/videx-wellog/blob/d9d1e76dcb606ee3431097edff07515b8ae68809/src/plots/interfaces.ts#L81)) for improved performance. This is automatically enabled for the factory functions. So you should be able to override this behaviour by setting this option to false in your config

**Comment by john-haugland** [comment]
Thank you. This solved the problem. Please close the issue.
